# Generated by Django 4.2.24 on 2025-09-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gargoyle', '0002_bytes_to_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='value',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
